In [1]:
import pandas as pd

## Selecting weather data only from California and Utah

In [2]:
#Import daily weather data
weather_df = pd.read_csv("weather_data.csv")

In [20]:
#Slice data for California and Utah
weather_utah_cali = weather_df[(weather_df['State Name']=='Utah')|(weather_df['State Name']=='California')]

In [ ]:
#Save to csv
weather_utah_cali.to_csv("utah_cali_daily_weather.csv",index=False)

## Selecting air quality and AQI data only from California and Utah

In [5]:
#Import daily air quality data
param_all = pd.read_csv("air_data_merged.csv", low_memory=False)

In [6]:
# Keeping only Utah and California
filtered_df = param_all[param_all['State Name'].isin(['Utah', 'California'])]
filtered_df

,State Code,State Name,County Code,County Name,City Name,Site Num,Datum,Latitude,Longitude,Date Local,...,NO2(ppm) Max Hour,PM2_5(µg/m³ LC),PM2_5(µg/m³ LC) Max Value,PM2_5(µg/m³ LC) Max Hour,PM10 Tot_0-10um STP(μg/m3),PM10 Tot_0-10um STP(μg/m3) Max Value,PM10 Tot_0-10um STP(μg/m3) Max Hour,CO(ppm),CO(ppm) Max Value,CO(ppm) Max Hour
8355775,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-01,...,4.0,2.500000,2.5,0.0,NaN,NaN,NaN,NaN,NaN,NaN
8355776,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-02,...,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8355777,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-03,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8355778,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-04,...,8.0,3.300000,3.3,0.0,6.0,6.0,0.0,NaN,NaN,NaN
8355779,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-05,...,21.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11871949,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-26,...,NaN,4.204167,9.0,16.0,14.0,14.0,23.0,NaN,NaN,NaN
11871950,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-27,...,NaN,5.929167,11.0,18.0,17.0,17.0,23.0,NaN,NaN,NaN
11871951,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-28,...,NaN,5.500000,10.0,0.0,17.0,17.0,23.0,NaN,NaN,NaN
11871952,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-29,...,NaN,7.020834,14.0,18.0,20.0,20.0,23.0,NaN,NaN,NaN
11871953,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-30,...,NaN,7.612500,13.0,16.0,21.0,21.0,23.0,NaN,NaN,NaN

In [ ]:
#Changing data types dtypes
filtered_df['State Code'] = filtered_df['State Code'].astype(int).astype(str)
filtered_df['County Code'] = filtered_df['County Code'].astype(int).astype(str)
filtered_df['Site Num'] = filtered_df['Site Num'].astype(int).astype(str)
filtered_df['Date Local'] = pd.to_datetime(filtered_df['Date Local'])

In [8]:
#Dropping unnecessary columns
filtered_df = filtered_df.drop(columns=['AQI', 'CBSA Name'])
filtered_df

,State Code,State Name,County Code,County Name,City Name,Site Num,Datum,Latitude,Longitude,Date Local,...,NO2(ppm) Max Hour,PM2_5(µg/m³ LC),PM2_5(µg/m³ LC) Max Value,PM2_5(µg/m³ LC) Max Hour,PM10 Tot_0-10um STP(μg/m3),PM10 Tot_0-10um STP(μg/m3) Max Value,PM10 Tot_0-10um STP(μg/m3) Max Hour,CO(ppm),CO(ppm) Max Value,CO(ppm) Max Hour
8355775,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-01,...,4.0,2.500000,2.5,0.0,NaN,NaN,NaN,NaN,NaN,NaN
8355776,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-02,...,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8355777,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-03,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8355778,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-04,...,8.0,3.300000,3.3,0.0,6.0,6.0,0.0,NaN,NaN,NaN
8355779,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-05,...,21.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11871949,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-26,...,NaN,4.204167,9.0,16.0,14.0,14.0,23.0,NaN,NaN,NaN
11871950,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-27,...,NaN,5.929167,11.0,18.0,17.0,17.0,23.0,NaN,NaN,NaN
11871951,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-28,...,NaN,5.500000,10.0,0.0,17.0,17.0,23.0,NaN,NaN,NaN
11871952,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-29,...,NaN,7.020834,14.0,18.0,20.0,20.0,23.0,NaN,NaN,NaN
11871953,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-30,...,NaN,7.612500,13.0,16.0,21.0,21.0,23.0,NaN,NaN,NaN

In [9]:
# Importing daily AQI csv
aqi = pd.read_csv("daily_AQI.csv")
aqi.head()

,State Code,State Name,County Code,County Name,City Name,Site Num,Datum,Latitude,Longitude,Date Local,CBSA Name,measurement_id,max_value,AQI_cr_param
0,10,Delaware,1,Kent,Not in a city,2,WGS84,38.986672,-75.5568,2004-01-01,"Dover, DE",10_1_2_20040101,32.0,AQI_PM2_5
1,10,Delaware,1,Kent,Not in a city,2,WGS84,38.986672,-75.5568,2004-01-04,"Dover, DE",10_1_2_20040104,60.0,AQI_PM2_5
2,10,Delaware,1,Kent,Not in a city,2,WGS84,38.986672,-75.5568,2004-01-07,"Dover, DE",10_1_2_20040107,26.0,AQI_PM2_5
3,10,Delaware,1,Kent,Not in a city,2,WGS84,38.986672,-75.5568,2004-01-10,"Dover, DE",10_1_2_20040110,28.0,AQI_PM2_5
4,10,Delaware,1,Kent,Not in a city,2,WGS84,38.986672,-75.5568,2004-01-13,"Dover, DE",10_1_2_20040113,35.0,AQI_PM2_5

In [10]:
#Keeping data only from California and Utah
aqi_utah_cal = aqi[aqi['State Name'].isin(['Utah', 'California'])]
aqi_utah_cal

,State Code,State Name,County Code,County Name,City Name,Site Num,Datum,Latitude,Longitude,Date Local,CBSA Name,measurement_id,max_value,AQI_cr_param
8355775,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-01,"Ogden-Clearfield, UT",49_11_4_20040101,10.0,AQI_NO2
8355776,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-02,"Ogden-Clearfield, UT",49_11_4_20040102,42.0,AQI_NO2
8355777,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-03,"Ogden-Clearfield, UT",49_11_4_20040103,41.0,AQI_NO2
8355778,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-04,"Ogden-Clearfield, UT",49_11_4_20040104,37.0,AQI_NO2
8355779,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-05,"Ogden-Clearfield, UT",49_11_4_20040105,44.0,AQI_NO2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11871949,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-26,NaN,6_9_1_20230626,41.0,AQI_ozone
11871950,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-27,NaN,6_9_1_20230627,43.0,AQI_ozone
11871951,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-28,NaN,6_9_1_20230628,44.0,AQI_ozone
11871952,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-29,NaN,6_9_1_20230629,51.0,AQI_ozone
11871953,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-30,NaN,6_9_1_20230630,61.0,AQI_ozone

In [15]:
#Merging AQI data for Utah and California in the df
aqi_utah_cali = pd.merge(filtered_df, aqi_utah_cal, on='measurement_id', how='outer')
aqi_utah_cali

,State Code_x,State Name_x,County Code_x,County Name_x,City Name_x,Site Num_x,Datum_x,Latitude_x,Longitude_x,Date Local_x,...,County Name_y,City Name_y,Site Num_y,Datum_y,Latitude_y,Longitude_y,Date Local_y,CBSA Name,max_value,AQI_cr_param
0,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-01,...,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-01,"Ogden-Clearfield, UT",10.0,AQI_NO2
1,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-02,...,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-02,"Ogden-Clearfield, UT",42.0,AQI_NO2
2,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-03,...,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-03,"Ogden-Clearfield, UT",41.0,AQI_NO2
3,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-04,...,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-04,"Ogden-Clearfield, UT",37.0,AQI_NO2
4,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-05,...,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-05,"Ogden-Clearfield, UT",44.0,AQI_NO2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1673379,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-26,...,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-26,NaN,41.0,AQI_ozone
1673380,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-27,...,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-27,NaN,43.0,AQI_ozone
1673381,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-28,...,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-28,NaN,44.0,AQI_ozone
1673382,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-29,...,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-29,NaN,51.0,AQI_ozone
1673383,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-30,...,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-30,NaN,61.0,AQI_ozone

In [16]:
merg_cols= aqi_utah_cali.columns

In [17]:
#Dropping unnecessary columns
aqi_utah_cali= aqi_utah_cali.drop(columns=aqi_utah_cali.filter(regex='_y$').columns)
aqi_utah_cali

,State Code_x,State Name_x,County Code_x,County Name_x,City Name_x,Site Num_x,Datum_x,Latitude_x,Longitude_x,Date Local_x,...,PM2_5(µg/m³ LC) Max Hour,PM10 Tot_0-10um STP(μg/m3),PM10 Tot_0-10um STP(μg/m3) Max Value,PM10 Tot_0-10um STP(μg/m3) Max Hour,CO(ppm),CO(ppm) Max Value,CO(ppm) Max Hour,CBSA Name,max_value,AQI_cr_param
0,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-01,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"Ogden-Clearfield, UT",10.0,AQI_NO2
1,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Ogden-Clearfield, UT",42.0,AQI_NO2
2,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Ogden-Clearfield, UT",41.0,AQI_NO2
3,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-04,...,0.0,6.0,6.0,0.0,NaN,NaN,NaN,"Ogden-Clearfield, UT",37.0,AQI_NO2
4,49,Utah,11,Davis,Bountiful,4,WGS84,40.902967,-111.884467,2004-01-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Ogden-Clearfield, UT",44.0,AQI_NO2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1673379,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-26,...,16.0,14.0,14.0,23.0,NaN,NaN,NaN,NaN,41.0,AQI_ozone
1673380,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-27,...,18.0,17.0,17.0,23.0,NaN,NaN,NaN,NaN,43.0,AQI_ozone
1673381,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-28,...,0.0,17.0,17.0,23.0,NaN,NaN,NaN,NaN,44.0,AQI_ozone
1673382,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-29,...,18.0,20.0,20.0,23.0,NaN,NaN,NaN,NaN,51.0,AQI_ozone
1673383,6,California,9,Calaveras,San Andreas,1,NAD83,38.201850,-120.680277,2023-06-30,...,16.0,21.0,21.0,23.0,NaN,NaN,NaN,NaN,61.0,AQI_ozone

In [18]:
#Renaming Columns
aqi_utah_cali.rename(columns={'State Code_x':'State Code', 'State Name_x':'State Name', 'County Code_x':'County Code', 'County Name_x':'County Name',
       'City Name_x':'City Name', 'Site Num_x':'Site Num', 'Datum_x':'Datum', 'Latitude_x':'Latitude', 'Longitude_x':'Longitude',
       'Date Local_x':'Date Local'},inplace=True)

In [ ]:
#Saving the final df for Utan and California to csv
aqi_utah_cali.to_csv("daily_Cal&Utah.csv", index=False, encoding='utf-8')

## Merging air quality and AQI with weather data

In [21]:
#Merge weather with air quality and AQI data
all_df = pd.merge(aqi_utah_cali, weather_utah_cali, how='outer',on='measurement_id')

In [22]:
#Fill left columns if NaN
for column in all_df.columns:
    if column.endswith('_x'):
        corresponding_column = column[:-2] + '_y'
        if corresponding_column in all_df.columns:
            all_df[column] = all_df[column].fillna(all_df[corresponding_column])

#Drop right columns
all_df = all_df.drop(columns=all_df.filter(regex='_y$').columns)

#Rename columns
all_df.rename(columns={'State Code_x':'State Code', 'State Name_x':'State Name', 'County Code_x':'County Code', 'County Name_x':'County Name',
       'City Name_x':'City Name', 'Site Num_x':'Site Num', 'Datum_x':'Datum', 'Latitude_x':'Latitude', 'Longitude_x':'Longitude',
       'Date Local_x':'Date Local','CBSA Name_x':'CBSA Name'},inplace=True)

In [ ]:
# Save to CSV
all_df.to_csv("utah_cali_all.csv",index=False)